src/Entity/Person.php
<?php
declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * We try to keep most fields as string, as we can have sometimes special characters
 * such as 28? with a question mark if someone is not sure about the age written
 */
#[ORM\Entity]
#[ORM\Table(name: 'person')]
class Person
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "CUSTOM")]
    #[ORM\CustomIdGenerator("doctrine.ulid_generator")]
    #[ORM\Column(length: 26)]
    private ?string $id = null;

    #[ORM\ManyToOne(targetEntity: Record::class, inversedBy: 'persons')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Record $record = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $surname = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $given_names = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $age = null;

    #[ORM\Column(length: 30, nullable: false)]
    private ?string $relationship = null;
    // one of: 'individual', 'spouse', 'father', 'mother', 'father_father', 'father_mother', 'mother_father', 'mother_mother', 'spouse_father_father', 'spouse_father_mother', 'spouse_mother_father', 'spouse_mother_mother'
    // can be extended later (godfather, witness, etc)

    /**
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @return Record|null
     */
    public function getRecord(): ?Record
    {
        return $this->record;
    }

    /**
     * @param Record|null $record
     * @return Person
     */
    public function setRecord(?Record $record): Person
    {
        $this->record = $record;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getSurname(): ?string
    {
        return $this->surname;
    }

    /**
     * @param string|null $surname
     * @return Person
     */
    public function setSurname(?string $surname): Person
    {
        $this->surname = $surname;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getGivenNames(): ?string
    {
        return $this->given_names;
    }

    /**
     * @param string|null $given_names
     * @return Person
     */
    public function setGivenNames(?string $given_names): Person
    {
        $this->given_names = $given_names;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getAge(): ?string
    {
        return $this->age;
    }

    /**
     * @param string|null $age
     * @return Person
     */
    public function setAge(?string $age): Person
    {
        $this->age = $age;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getRelationship(): ?string
    {
        return $this->relationship;
    }

    /**
     * @param string|null $relationship
     * @return Person
     */
    public function setRelationship(?string $relationship): Person
    {
        $this->relationship = $relationship;
        return $this;
    }

    public function __toString()
    {
        return $this->surname . ' ' . $this->given_names . ': '.$this->relationship;
    }
}

src/Controller/SearchController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Record;
use App\Form\SearchFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/{_locale<%app.supported_locales%>}/search')]
class SearchController extends AbstractController
{
    #[Route('', name: 'search_advanced', methods: ["GET"])]
    public function advanced(Request $request, FormFactoryInterface $formFactory, EntityManagerInterface $entityManager): Response
    {
        $form = $formFactory->createBuilder(SearchFormType::class)
            ->setAction($this->generateUrl('search_results'))
            ->getForm();
        $form->handleRequest($request);
        return $this->render('search/advanced.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/results', name: 'search_results', methods: ["GET", "POST"])]
    public function results(Request $request, FormFactoryInterface $formFactory, EntityManagerInterface $entityManager): Response
    {
        $form = $formFactory->createBuilder(SearchFormType::class)->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            // TODO: Paginate results
            $records = $entityManager->getRepository(Record::class)->manualSearch($data);

            // TODO: If no result found, find approximate Levenshtein names

            return $this->render('search/results.html.twig', [
                'records' => $records
            ]);
        }

        // FIXME: Don't show index page here, make a forbidden page
        return $this->render('index.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/search/advanced.html.twig
{% extends 'base.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <h2 id="search">Advanced search</h2>
    <p>Advanced search is not available yet. In the meantime, you can use the simple search.</p>

    {{ form_start(form) }}
    <p>Currently, only exact search is supported. Fuzzy search will come later.</p>
    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.surname, {'attr': {'class': 'form-control-lg'}}) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.given_names, {'attr': {'class': 'form-control-lg'}}) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.location, {'attr': {'class': 'form-control-lg'}}) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.year, {'attr': {'class': 'form-control-lg'}}) }}
        </div>
    </div>
    <button class="btn btn-lg btn-primary">Search</button>
    {{ form_end(form) }}
{% endblock %}

templates/search/results.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search results{% endblock %}

{% block content %}
    <h3 id="result">Search results</h3>
    {% if records|length %}
        <div class="table-responsive">
            <table class="table w-auto">
                <thead>
                <tr>
                    <th>Person</th>
                    <th>Events</th>
                    <th>Details</th>
                </tr>
                </thead>
                <tbody>
                {% for record in records %}
                    <tr>
                        <td>
                            {% for person in record.persons|filter(p => p.relationship == 'individual') %}
                                <strong>{{ person.surname }} {{ person.givenNames }}</strong>
                            {% endfor %}
                        </td>
                        <td>
                            {% for event in record.events %}
                                <strong>{{ event.type }}:</strong> {{ event.year }}
                            {% endfor %}
                        </td>
                        <td>
                            <a href="{{ path('record_view', {id: record.id}) }}">Access</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <hr/>
    {% else %}
        <p><em>No result found.</em></p>
    {% endif %}
{% endblock %}